import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Prodigi's own site content, generated by scripts/sync-knowledge.mjs from
 * src/content/*.ts (the frontend's single source of truth — see that script
 * for how to regenerate after editing site copy). Used to ground chat,
 * search and agent responses so the model answers only from what the site
 * actually says, with the same entity description everywhere (GEO).
 */
export interface KnowledgeFaq {
  id: string;
  question: string;
  answer: string;
}

export interface KnowledgePage {
  title: string;
  path: string;
  lead: string;
  definition: { question: string; answer: string };
  offerings: string[];
}

export interface Knowledge {
  generatedAt: string;
  entity: {
    name: string;
    legalName: string;
    acronym: string;
    category: string;
    summary: string;
    definition: string;
    principle: string;
    audience: string;
    problem: string;
    capabilities: string[];
  };
  pillars: { name: string; verb: string; description: string; path: string }[];
  intelligenceCapabilities: { name: string; summary: string; examples: string[]; path: string }[];
  pages: KnowledgePage[];
  faqs: KnowledgeFaq[];
}

const dir = dirname(fileURLToPath(import.meta.url));
export const knowledge: Knowledge = JSON.parse(readFileSync(join(dir, 'prodigi-knowledge.json'), 'utf8'));

/** One retrievable document per knowledge entry, used for embedding-based search. */
export interface KnowledgeDoc {
  id: string;
  title: string;
  path: string;
  category: 'faq' | 'page' | 'capability' | 'pillar';
  text: string;
}

export function flattenKnowledge(): KnowledgeDoc[] {
  const docs: KnowledgeDoc[] = [];
  for (const faq of knowledge.faqs) {
    docs.push({ id: `faq:${faq.id}`, title: faq.question, path: '/resources', category: 'faq', text: `${faq.question}\n${faq.answer}` });
  }
  for (const page of knowledge.pages) {
    docs.push({
      id: `page:${page.path}`,
      title: page.title,
      path: page.path,
      category: 'page',
      text: [page.title, page.lead, page.definition.question, page.definition.answer, ...page.offerings].join('\n'),
    });
  }
  for (const capability of knowledge.intelligenceCapabilities) {
    docs.push({
      id: `capability:${capability.path}`,
      title: capability.name,
      path: capability.path,
      category: 'capability',
      text: `${capability.name}: ${capability.summary}\nExamples: ${capability.examples.join(', ')}`,
    });
  }
  for (const pillar of knowledge.pillars) {
    docs.push({ id: `pillar:${pillar.path}`, title: pillar.name, path: pillar.path, category: 'pillar', text: `${pillar.name} — ${pillar.verb}\n${pillar.description}` });
  }
  return docs;
}

/** System instruction shared by chat and the agent — keeps every surface answering consistently. */
export function buildSystemInstruction(): string {
  const { entity } = knowledge;
  return [
    `You are Prodigi Intelligence, the applied-AI voice of ${entity.name} (${entity.legalName}).`,
    `Entity: ${entity.definition}`,
    `Principle: ${entity.principle}`,
    `Audience: ${entity.audience}. Problem Prodigi solves: ${entity.problem}.`,
    `Capabilities: ${entity.capabilities.join(', ')}.`,
    '',
    'Rules:',
    '- Answer only from the Prodigi context you are given or already know from this instruction. If you do not know, say so plainly — never invent facts, pricing, clients, or integrations.',
    '- Keep answers concise and concrete: 2-4 sentences unless the visitor asks for more detail.',
    '- Speak as "Prodigi", not as a generic AI assistant. Do not mention being Gemini or Google.',
    '- When relevant, suggest the one most relevant next step (a page to visit, or starting a conversation at /contact).',
    '- Never fabricate case studies, client names, statistics, or certifications.',
  ].join('\n');
}
